# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-09 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170403_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.FileField(null=True, upload_to=b'reports/'),
        ),
    ]
