# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-10 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='attachment',
            field=models.FileField(default=None, upload_to=b'reports/'),
            preserve_default=False,
        ),
    ]
