# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20170423_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportattachment',
            name='encryptedattachment',
            field=models.FileField(blank=True, upload_to=b'reports/'),
        ),
    ]
