# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-17 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170410_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attachmenthash',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, upload_to=b'reports/'),
        ),
    ]
