# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='company_email',
            field=models.EmailField(max_length=255),
        ),
    ]
