# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20170430_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='industry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Industry'),
        ),
        migrations.AlterField(
            model_name='report',
            name='sector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Sector'),
        ),
    ]
